version: '3'

services:
  neo4j:
    build: ./neo4j
    # image: neo4j:4.4
    container_name: predictor_neo4j
    network_mode: bridge
    # user: 1000 1000
    # volumes:
    #   - type: bind
    #     source: /c/Users/Darren/projects/github/predictors/nfl/neo4j/import
    #     target: /var/lib/neo4j/import
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/letmein
      - NEO4JLABS_PLUGINS=["apoc","graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,gds.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_allow__upgrade=true
